os: linux
dist: focal

language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - gcc-10
      - g++-10
      - cmake
      - clang-tidy
      - lcov

script:
  - /usr/bin/gcc-10 -v && /usr/bin/g++ -v && cmake --version
  - cmake -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_C_COMPILER=/usr/bin/gcc-10
  - cmake --build build
  - ctest -S cmake/run_tests.cmake